const INCREMENT_COUNTER = "counter/INCREMENT_COUNTER";
const DECREMENT_COUNTER = "counter/DECREMENT_COUNTER";
const INCREMENT_COUNTER_ASYNC = "counter/INCREMENT_COUNTER_ASYNC";

export {
  DECREMENT_COUNTER,
  INCREMENT_COUNTER,
  INCREMENT_COUNTER_ASYNC
}